- name: Check installer exists
  win_stat:
    path: c:\Users\vagrant\splunkforwarder-9.1.2-b6b9c8185839-x64-release.msi
  register: installer_file

- name: Download Installer
  win_get_url:
    url: "https://download.splunk.com/products/universalforwarder/releases/9.1.2/windows/splunkforwarder-9.1.2-b6b9c8185839-x64-release.msi"
    dest: 'c:\Users\vagrant\splunkforwarder-9.1.2-b6b9c8185839-x64-release.msi'
  when: not installer_file.stat.exists

- name: Check Splunk Exists
  win_stat:
    path: "C:\\Program Files\\SplunkUniversalForwarderi\\bin\\splunk.exe"
  register: splunk_installed

- name: Remove Splunk
  win_command: msiexec.exe /x C:\Users\vagrant\splunkforwarder-9.1.2-b6b9c8185839-x64-release.msi /q
